mage_python/Ex/13/homework/messages/messages/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.views.generic import RedirectView

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^online/', include('online.urls', namespace='online')),
    url(r'^user/', include('user.urls', namespace='user')),
    url(r'^$', RedirectView.as_view(url='/user/require_login/')),
]

mage_python/Ex/13/homework/messages/user/urls.py
#encoding: utf-8
from django.conf.urls import url

from . import views


urlpatterns = [
    url(r'^require_login/', views.require_login, name='require_login'),
    url(r'^login/', views.login, name='login'),
    url(r'^list_user/', views.list_user, name='list_user'),
    url(r'^delete_user/', views.delete_user, name='delete_user'),
    url(r'^create_user/', views.create_user, name='create_user'),
    url(r'^save_user/', views.save_user, name='save_user'),
    url(r'^view_user/', views.view_user, name='view_user'),
    url(r'^modify_user/', views.modify_user, name='modify_user'),
    url(r'^logout/', views.logout, name='logout'),
    url(r'^modify_password/', views.modify_password, name='modify_password'),
]

mage_python/Ex/13/homework/messages/user/models.py
#encoding: utf-8

import json

from django.db import models

class User2(models.Model):
    username = models.CharField(max_length=64)
    password = models.CharField(max_length=512)
    age = models.IntegerField()
    tel = models.CharField(max_length=13)

    def as_dict(self):
        return {'id' : self.id, 'username' : self.username, 'age' : self.age, 'tel' : self.tel}

    def __str__(self):
        return json.dumps(self.as_dict())

mage_python/Ex/13/homework/messages/user/forms.py
#encoding: utf-8

from django import forms
from django.core.exceptions import ObjectDoesNotExist

from . import models
from utils import crypt

class LoginForm(forms.Form):
    username = forms.CharField(label="用户名", required=False)
    password = forms.CharField(widget=forms.PasswordInput, label="密码", required=False)

    def clean(self):
        cleaned_data = super(LoginForm, self).clean()

        username = cleaned_data.get('username', '')
        password = cleaned_data.get('password', '')
        if username == '' or password == '':
            raise forms.ValidationError('用户名或密码为空')

        password = crypt.CryptUtils.md5(password)
        count = models.User2.objects.filter(username=username, password=password).count()
        if count == 0:
            raise forms.ValidationError("用户名或密码错误")
        # try:
        #     models.User2.objects.get(username=username, password=password)
        # except ObjectDoesNotExist as e:
        #     raise forms.ValidationError("用户名或密码错误")
        return cleaned_data


class CreateUserForm(forms.Form):
    username = forms.CharField(label="用户名", error_messages={'required' : "用户名不能为空"})
    password = forms.CharField(widget=forms.PasswordInput, label="密码", error_messages={'required' : "密码不能为空"})
    age = forms.CharField(label="年龄", error_messages={'required' : "年龄不能为空"})
    tel = forms.CharField(label="电话号码", error_messages={'required' : "电话号码不能为空"})

    def clean_username(self):
        username = self.cleaned_data.get('username', '')
        try:
            models.User2.objects.get(username=username)
            raise forms.ValidationError("用户名已存在")
        except ObjectDoesNotExist as e:
            pass

        return username

    def clean_password(self):
        password = self.cleaned_data.get('password', '')
        return crypt.CryptUtils.md5(password)

    def clean_age(self):
        age = self.cleaned_data.get('age', 0)
        if not str(age).isdigit():
            raise forms.ValidationError("年龄必须为0到80的整数")

        age = int(age)
        if age <= 0 or age >= 80:
            raise forms.ValidationError("年龄必须为0到80的整数")
        return age

    def clean_tel(self):
        tel = self.cleaned_data.get('tel', '')
        if len(tel) != 11:
            raise forms.ValidationError("手机号码不正确")

        return tel


class ModifyUserForm(forms.Form):
    id = forms.CharField(widget=forms.HiddenInput, required=False)
    username = forms.CharField(label="用户名", error_messages={'required' : "用户名不能为空"})
    age = forms.CharField(label="年龄", error_messages={'required' : "年龄不能为空"})
    tel = forms.CharField(label="电话号码", error_messages={'required' : "电话号码不能为空"})

    def clean(self):
        cleaned_data = super(ModifyUserForm, self).clean()
        try:
            _id = cleaned_data.get('id', 0)
            if not str(_id).isdigit():
                raise forms.ValidationError("操作对象不存在")
            models.User2.objects.get(pk=_id)
        except ObjectDoesNotExist as e:
            raise forms.ValidationError("操作对象不存在")

        return cleaned_data

    def clean_username(self):
        username = self.cleaned_data.get('username', '')
        try:
            _id = self.cleaned_data.get('id', 0)
            if not str(_id).isdigit():
                raise forms.ValidationError("操作对象不存在")
            models.User2.objects.exclude(pk=_id).get(username=username)
            raise forms.ValidationError("用户名已存在")
        except ObjectDoesNotExist as e:
            pass

        return username

    def clean_age(self):
        age = self.cleaned_data.get('age', 0)
        if not str(age).isdigit():
            raise forms.ValidationError("年龄必须为0到80的整数")

        age = int(age)
        if age <= 0 or age >= 80:
            raise forms.ValidationError("年龄必须为0到80的整数")
        return age

    def clean_tel(self):
        tel = self.cleaned_data.get('tel', '')
        if len(tel) != 11:
            raise forms.ValidationError("手机号码不正确")

        return tel


class PasswordForm(forms.Form):
    id = forms.CharField(widget=forms.HiddenInput, required=False)
    password = forms.CharField(widget=forms.PasswordInput, label="密码", error_messages={'required' : "密码不能为空"})

    def clean(self):
        cleaned_data = super(PasswordForm, self).clean()
        try:
            id = cleaned_data.get('id', 0)
            models.User2.objects.get(pk=id)
        except ObjectDoesNotExist as e:
            raise forms.ValidationError("操作对象不存在")

        return cleaned_data


    def clean_password(self):
        password = self.cleaned_data.get('password', '')
        return crypt.CryptUtils.md5(password)

mage_python/Ex/13/homework/messages/user/views.py
from django.shortcuts import render

from django.http import HttpResponse, HttpResponseRedirect
from django.core.exceptions import ObjectDoesNotExist
from django.urls import reverse

from . import models
from .forms import LoginForm, CreateUserForm, ModifyUserForm, PasswordForm

# Create your views here.

def require_login(request):
    if request.session.get('user'):
        return HttpResponseRedirect(reverse('user:list_user'))

    form = LoginForm(initial={'username': '', 'password': ''})
    return render(request, 'user/login.html', {'form': form})


def login(request):

    if request.session.get('user'):
        return HttpResponseRedirect(reverse('user:list_user'))

    form = LoginForm(request.POST)
    if form.is_valid():
        request.session['user'] = {'username' : form.cleaned_data['username']}
        return HttpResponseRedirect(reverse('user:list_user'))
    else:
        return render(request, 'user/login.html', {'form' : form})


def list_user(request):
    if request.session.get('user') is None:
        return HttpResponseRedirect(reverse('user:require_login'))
    users = models.User2.objects.all()
    return render(request, 'user/list.html', {'users' : users})


def delete_user(request):
    if request.session.get('user') is None:
        return HttpResponseRedirect(reverse('user:require_login'))
    _id = request.GET.get('id', '')
    user = None
    try:
        uid = request.GET.get('id', 0)
        user = models.User2.objects.get(pk=_id)
        user.delete()
    except ObjectDoesNotExist as e:
        pass
    return HttpResponseRedirect(reverse('user:list_user'))


def create_user(request):
    if request.session.get('user') is None:
        return HttpResponseRedirect(reverse('user:require_login'))
    form = CreateUserForm(initial={'username': '', 'password': '', 'age': '', 'tel': ''})
    return render(request, 'user/create.html', {'form' : form})


def save_user(request):
    if request.session.get('user') is None:
        return HttpResponseRedirect(reverse('user:require_login'))

    form = CreateUserForm(request.POST)
    if form.is_valid():
        user = models.User2(username=form.cleaned_data['username'], password=form.cleaned_data['password'], age=form.cleaned_data['age'], tel=form.cleaned_data['tel'])
        user.save()
        return HttpResponseRedirect(reverse('user:list_user'))
    else:
        return render(request, 'user/create.html', {'form': form})


def view_user(request):
    if request.session.get('user') is None:
        return HttpResponseRedirect(reverse('user:require_login'))
    form = None
    try:
        _id = request.GET.get('id', 0)
        user = models.User2.objects.get(pk=_id)
        form = ModifyUserForm(user.as_dict())
    except ObjectDoesNotExist as e:
        form = ModifyUserForm()
    return render(request, 'user/view.html', {'form': form})

def modify_user(request):
    if request.session.get('user') is None:
        return HttpResponseRedirect(reverse('user:require_login'))

    form = ModifyUserForm(request.POST)
    if form.is_valid():
        user = models.User2.objects.get(pk=form.cleaned_data['id'])
        user.username = form.cleaned_data['username']
        user.age = form.cleaned_data['age']
        user.tel = form.cleaned_data['tel']
        user.save()
        return HttpResponseRedirect(reverse('user:list_user'))
    else:
        return render(request, 'user/view.html', {'form': form})

def modify_password(request):
    if request.session.get('user') is None:
        return HttpResponseRedirect(reverse('user:require_login'))

    form = None
    if request.method == 'GET':
        try:
            _id = request.GET.get('id', 0)
            user = models.User2.objects.get(pk=_id)
            form = PasswordForm(initial={'password': '', 'id': _id})
        except ObjectDoesNotExist as e:
            form = PasswordForm()
    else:
        form = PasswordForm(request.POST)
        if form.is_valid():
            user = models.User2.objects.get(pk=form.cleaned_data['id'])
            user.password = form.cleaned_data['password']
            user.save()
            return HttpResponseRedirect(reverse('user:list_user'))

    return render(request, 'user/password.html', {'form': form})

def logout(request):
    request.session.flush()
    return HttpResponseRedirect(reverse('user:require_login'))

mage_python/Ex/13/homework/messages/user/templates/user/create.html
{% extends "base.html" %}

{% block title %} 用户添加 {% endblock %}

{% block styles %}
<style type="text/css">
    li {
        list-style-type:none;
        color: red;
        font-weight: 900;
    }
</style>
{% endblock %}

{% block content %}
<form class="form-horizontal" action="{% url 'user:save_user' %}" method="POST" novalidate="novalidate">
    {% csrf_token %}
    <div class="form-group">
        {{ form.username.errors }}
        <label class="col-sm-1 control-label">用户名：</label>
        <div class="col-sm-11">
            <input class="form-control" type="text" name="username" value="{{ form.username.value }}">
        </div>
    </div>
    <div class="form-group">
        {{ form.password.errors }}
        <label class="col-sm-1 control-label">密码：</label>
        <div class="col-sm-11">
            <input class="form-control" type="password" name="password" value="{{ form.password.value }}">
        </div>
    </div>
    <div class="form-group">
        {{ form.age.errors }}
        <label class="col-sm-1 control-label">年龄：</label>
        <div class="col-sm-11">
            <input class="form-control" type="text" name="age" value="{{ form.age.value }}">
        </div>
    </div>
    <div class="form-group">
        {{ form.tel.errors }}
        <label class="col-sm-1 control-label">电话号码：</label>
        <div class="col-sm-11">
            <input class="form-control" type="text" name="tel" value="{{ form.tel.value }}">
        </div>
    </div>
    <button type="submit" class="btn btn-primary">添加</button>
</form>
{% endblock %}

mage_python/Ex/13/homework/messages/user/templates/user/list.html
{% extends "base.html" %}

{% load staticfiles %}

{% block title %} 用户列表 {% endblock %}

{% block links %}
<link rel="stylesheet" type="text/css" href="{% static 'user/page.css' %}" />
{% endblock %}

{% block nav_user %} class="active" {% endblock %}

{% block content %}
<a href="{% url 'user:create_user' %}">添加</a>
欢迎 {{ request.session.user.username }},<a href="{% url 'user:logout' %}">退出登录</a>
<table class="table table-striped table-bordered table-hover table-condensed">
    <thead>
        <tr>
            <th>名字</th>
            <th>年龄</th>
            <th>电话号码</th>
            <th>操作</th>
        </tr>
    </thead>
    <tbody>
    {% for user in users %}
        <tr>
            <td>{{ user.username }}</td>
            <td>{{ user.age }}</td>
            <td>{{ user.tel }}</td>
            <td>
                <a href="{% url 'user:view_user' %}?id={{ user.id }}">
                    <button type="button" class="btn btn-primary btn-xs">编辑</button>
                </a>
                <a href="{% url 'user:modify_password' %}?id={{ user.id }}">
                    <button type="submit" class="btn btn-warning btn-xs">修改密码</button>
                </a>
                <a href="{% url 'user:delete_user' %}?id={{ user.id }}">
                    <button type="submit" class="btn btn-danger btn-xs">删除</button>
                </a>
            </td>
        </tr>
    {% endfor %}
    </tbody>
</table>
{% endblock %}

mage_python/Ex/13/homework/messages/user/templates/user/login.html
{% load staticfiles %}

<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8" />
        <title>用户登录</title>
        <link rel="stylesheet" type="text/css" href="{% static 'bootstrap-3.3.7-dist/css/bootstrap.min.css' %}" />
    </head>
    <body>
        <div class="container-fluid">
            <div class="row">
                <div class="col-md-2 col-md-offset-5" style="margin-top:100px">
                    <h1>用户登录</h1>
                    {{ form.non_field_errors }}
                    <form class="form-horizontal" action="{% url 'user:login' %}" method="POST" novalidate="novalidate">
                    {% csrf_token %}
                    <div class="form-group">
                        <label for="{{ form.username.id_for_label }}" class="sr-only col-sm-2 control-label">{{ form.username.label }}</label>
                        <div class="col-sm-12">
                            <input type="text" class="form-control" id="{{ form.username.id_for_label }}" name="{{ form.username.html_name }}" placeholder="{{ form.username.label }}" value="{{ form.username.value }}">
                        </div>
                    </div>
                    <div class="form-group">
                        <label for="{{ form.password.id_for_label }}" class="sr-only col-sm-2 control-label">{{ form.password.label }}</label>
                        <div class="col-sm-12">
                            <input type="password" class="form-control" id="{{ form.password.id_for_label }}" name="{{ form.password.html_name }}" placeholder="{{ form.password.label }}">
                        </div>
                    </div>
                    <div class="form-group">
                        <div class="col-sm-12">
                            <button type="submit" class="btn btn-primary btn-block">登录</button>
                        </div>
                    </div>
                </form>
                </div>
            </div>
        </div>
    </body>
</html>

mage_python/Ex/13/homework/messages/user/templates/user/password.html
{% extends "base.html" %}

{% block title %} 用户密码修改 {% endblock %}

{% block styles %}
<style type="text/css">
    li {
        list-style-type:none;
        color: red;
        font-weight: 900;
    }
</style>
{% endblock %}

{% block content %}
<form class="form-horizontal" action="{% url 'user:modify_password' %}" method="POST" novalidate="novalidate">
    {% csrf_token %}
    <div class="form-group">
        <input class="form-control" type="hidden" name="id" value="{{ form.id.value }}" />
    </div>
    <div class="form-group">
        {{ form.password.errors }}
        <label class="col-sm-1 control-label">密码：</label>
        <div class="col-sm-11">
            <input class="form-control" type="text" name="password" value="{{ form.password.value }}" />
        </div>
    </div>
    <button type="submit" class="btn btn-primary">修改</button>
</form>
{% endblock %}

mage_python/Ex/13/homework/messages/user/templates/user/view.html
{% extends "base.html" %}

{% block title %} 用户编辑 {% endblock %}

{% block styles %}
<style type="text/css">
    li {
        list-style-type:none;
        color: red;
        font-weight: 900;
    }
</style>
{% endblock %}

{% block content %}
<form class="form-horizontal" action="{% url 'user:modify_user' %}" method="POST" novalidate="novalidate">
    {% csrf_token %}
    <div class="form-group">
        <input class="form-control" type="hidden" name="id" value="{{ form.id.value }}" />
    </div>
    <div class="form-group">
        {{ form.username.errors }}
        <label class="col-sm-1 control-label">用户名：</label>
        <div class="col-sm-11">
            <input class="form-control" type="text" name="username" value="{{ form.username.value }}" />
        </div>
    </div>
    <div class="form-group">
        {{ form.age.errors }}
        <label class="col-sm-1 control-label">年龄：</label>
        <div class="col-sm-11">
            <input class="form-control" type="text" name="age" value="{{ form.age.value }}">
        </div>
    </div>
    <div class="form-group">
        {{ form.tel.errors }}
        <label class="col-sm-1 control-label">电话号码：</label>
        <div class="col-sm-11">
            <input class="form-control" type="text" name="tel" value="{{ form.tel.value }}">
        </div>
    </div>
    <button type="submit" class="btn btn-primary">修改</button>
</form>
{% endblock %}